{
    "sourceFile": "node_modules/es-abstract/2024/IteratorClose.js",
    "activeCommit": 0,
    "commits": [
        {
            "activePatchIndex": 0,
            "patches": [
                {
                    "date": 1746892173299,
                    "content": "Index: \n===================================================================\n--- \n+++ \n"
                }
            ],
            "date": 1746891704042,
            "name": "cart",
            "content": "'use strict';\n\nvar $TypeError = require('es-errors/type');\n\nvar Call = require('./Call');\nvar CompletionRecord = require('./CompletionRecord');\nvar GetMethod = require('./GetMethod');\nvar IsCallable = require('./IsCallable');\n\nvar isObject = require('../helpers/isObject');\nvar isIteratorRecord = require('../helpers/records/iterator-record');\n\n// https://262.ecma-international.org/15.0/#sec-iteratorclose\n\nmodule.exports = function IteratorClose(iteratorRecord, completion) {\n\tif (!isIteratorRecord(iteratorRecord)) {\n\t\tthrow new $TypeError('Assertion failed: `iteratorRecord` must be an Iterator Record'); // step 1\n\t}\n\tif (!isObject(iteratorRecord['[[Iterator]]'])) {\n\t\tthrow new $TypeError('Assertion failed: iteratorRecord.[[Iterator]] must be an Object'); // step 1\n\t}\n\n\tif (!IsCallable(completion) && !(completion instanceof CompletionRecord)) { // step 2\n\t\tthrow new $TypeError('Assertion failed: completion is not a thunk representing a Completion Record, nor a Completion Record instance');\n\t}\n\tvar completionThunk = completion instanceof CompletionRecord ? function () { return completion['?'](); } : completion;\n\n\tvar iterator = iteratorRecord['[[Iterator]]']; // step 3\n\n\tvar iteratorReturn;\n\ttry {\n\t\titeratorReturn = GetMethod(iterator, 'return'); // step 4\n\t} catch (e) {\n\t\tcompletionThunk(); // throws if `completion` is a throw completion // step 6\n\t\tcompletionThunk = null; // ensure it's not called twice.\n\t\tthrow e; // step 7\n\t}\n\tif (typeof iteratorReturn === 'undefined') {\n\t\treturn completionThunk(); // step 5.a - 5.b\n\t}\n\n\tvar innerResult;\n\ttry {\n\t\tinnerResult = Call(iteratorReturn, iterator, []);\n\t} catch (e) {\n\t\t// if we hit here, then \"e\" is the innerResult completion that needs re-throwing\n\n\t\tcompletionThunk(); // throws if `completion` is a throw completion // step 6\n\t\tcompletionThunk = null; // ensure it's not called twice.\n\n\t\t// if not, then return the innerResult completion\n\t\tthrow e; // step 7\n\t}\n\tvar completionRecord = completionThunk(); // if innerResult worked, then throw if the completion does\n\tcompletionThunk = null; // ensure it's not called twice.\n\n\tif (!isObject(innerResult)) {\n\t\tthrow new $TypeError('iterator .return must return an object');\n\t}\n\n\treturn completionRecord;\n};\n"
        }
    ]
}